### ISSUE TITLE
Enable authentication in config

### ISSUE THREAD

**Issue by catalinvr** [One-Model/simple-cerebro-cookbook#2]
Hi,

A few time ago I have created a pull request that enables authentication on cerebro config. #1 
Also this allows to connect to Elasticsearch when self-signed certificates were created.

Do you think that will be a good idea to merge in master the latest release?

Thank you

**Comment by dovicn** [comment]
Hi, sorry I must have missed the original addition. I've approved and merged in the changes you had requested.

Thanks for contributing!

**Comment by catalinvr** [comment]
Thank you @dovicn
